config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ideas do
    resources :reviews
    member do
      put "like", to: "ideas#upvote"
      put "dislike", to: "ideas#downvote"
    end
  end
  root 'ideas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  acts_as_votable
  has_many :reviews, dependent: :destroy
  belongs_to :user

  after_initialize :init

  validates(:title, { presence: true, uniqueness: true })
  validates(:text,{ presence: true, length: { minimum: 10 } })

  def init
    self.members  ||= 0           #will set the default value only if it's nil
    self.likes    ||= 0 #let's you set a default association
  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ideas
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @idea = Idea.all
  end

  def new
    @idea = Idea.new
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user

    if @idea.save
      redirect_to @idea
    else
      render 'new'
    end
  end

  def update
    @idea = Idea.find(params[:id])

    if @idea.update(idea_params)
      redirect_to @idea
    else
      render 'edit'
    end
  end

  def show
    @idea = Idea.find(params[:id])
    # @user = User.find(@idea.user_id)
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_path
  end

  def upvote
    @idea = Idea.find(params[:id])
    @idea.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @idea = Idea.find(params[:id])
    @idea.downvote_by current_user
    redirect_to :back
  end
  private

  def idea_params
    params.require(:idea).permit(:title, :text)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!

  def create
    @idea = Idea.find(params[:idea_id])
    @review = @idea.reviews.create(review_params)
    @review.user = current_user
    @review.save
    redirect_to idea_path(@idea)
  end

  def destroy
    @idea = Idea.find(params[:idea_id])
    @review = @idea.reviews.find(params[:id])
    @review.destroy
    if @review.save
      redirect_to idea_path(@idea)
    end

  end
  private

  def review_params
    params.require(:review).permit(:reviewer, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/ideas/_form.html.erb
<div id="contact-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">New Post</h4>
      </div>
      <%= form_for :idea, url: ideas_path do |f| %>
          <% if @idea.errors.any? %>
              <div id="error_explanation">
                <h2>
                  <%= pluralize(@idea.errors.count, "error") %> prohibited
                  this article from being saved:
                </h2>
                <ul>
                  <% @idea.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
          <div class="modal-body">
            <div class="form-group">
              <%= f.label :title %><br>
              <%= f.text_field :title %>
            </div>
            <div class="form-group">
              <%= f.label :text %><br>
              <%= f.text_area :text %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit class: 'btn btn-primary' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ideas/edit.html.erb
<h1>Edit idea</h1>

<%= form_for :idea, url: idea_path, method: :patch do |f| %>

    <% if @idea.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@idea.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @idea.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', idea_path(@idea) %>

app/views/ideas/index.html.erb
  <h1>Ideas</h1>


    <% @idea.each do |idea| %>
        <div class = 'well'>
          <div class="idea-title">
            <h4 style="margin-top:0"><%= idea.title %></h4>
            <div class="idea-body"><p><%= idea.text %></p></div>
          </div>
          <a href="#"><%=User.find(idea.user_id).email%></a>

          <div class="btn btn-xs btn-default">
            <%= link_to 'Show', idea_path(idea), :class => "btn-xs" %>
          </div>

          <div class="pull-right">
            <span>Members: <%= idea.members %></span>
            <%= link_to like_idea_path(idea), method: :put do %>
                Like
                <%= idea.get_upvotes.size %>
            <% end %>

          </div>


        </div>
    <% end %>
  </table>

app/views/ideas/new.html.erb
<h1>newnew</h1>

<%= form_for :idea, url: ideas_path do |f| %>

    <% if @idea.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@idea.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @idea.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/new.js.erb
$('<%= j render "form" %>').modal();

app/views/ideas/show.html.erb
<div class="well">
<h1><%= @idea.title %></h1>

<% if current_user %>
    <% @user = User.find(@idea.user_id) %>

    <h5>by: <%= @user.email %></h5>
<% end %>
  <br>
<p><%= @idea.text %></p>

<br>
<% if current_user%>
    <% if @user == current_user %>
        <%= link_to 'Edit', edit_idea_path(@idea) %> |
        <%= link_to 'Destroy', idea_path(@idea), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
<% end %>
</div>

<hr>
<h2>Reviews</h2>
<hr>

<% @idea.reviews.each do |review| %>
  <div class="well">
    <p>
      <strong>Reviewer:</strong>
      <%= User.find(review.user_id).email %>
    </p>

    <p>
      <strong>Review:</strong>
      <%= review.body %>
    </p>
    <%if review.user_id == current_user&.id%>
      <p>
        <%= link_to 'Destroy Review', [review.idea, review],
                    method: :delete,
                    data: {confirm: 'Are you sure?'} %>
      </p>
    <% end %>
  </div>
<% end %>
<hr>

<% if current_user %>
  <h2>Add a review:</h2>
  <%= form_for([@idea, @idea.reviews.build]) do |f| %>
      <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
      </p>
      <p>
        <%= f.submit %>
      </p>
  <% end %>
<% end %>

<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="navbar-text pull-left">
      <div>
        <a href="/">home</a>
      </div>
    </div>
    <div class="navbar-text pull-right">
      <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      <div>
        <%= link_to 'new idea', new_idea_path, remote: true, class: 'btn btn-xs btn-default' %>
      </div>
    </div>
  </nav>
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>